# TODO This resource should be created condidionally based on the provider or only the part of the provider should be created conditionally
---
{{- if .Values.clusterSecretStores.aws -}}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStores.aws.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    lentidas-stack.io: "true"
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.clusterSecretStores.aws.region }}
      auth:
        {{ if .Values.clusterSecretStores.aws.useRole }}
        jwt:
          serviceAccountRef:
            name: {{ .Release.Name }}-external-secrets
            namespace: {{ .Release.Namespace }}
        {{ end }}
        {{ if .Values.clusterSecretStores.aws.useAccessKey }}
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Release.Name }}-aws-secrets-manager-credentials
            key: access-key
            namespace: {{ .Release.Namespace }}
          secretAccessKeySecretRef:
            name: {{ .Release.Name }}-aws-secrets-manager-credentials
            key: secret-key
            namespace: {{ .Release.Namespace }}
        {{ end }}
{{- end -}}
