argo-cd:
  configs:
    cm:
      admin.enabled: "true"
      accounts.terraform: apiKey
      resource.customizations: |
        argoproj.io/Application: # https://argo-cd.readthedocs.io/en/stable/operator-manual/health/#argocd-app
          health.lua: |
            hs = {}
            hs.status = "Progressing"
            hs.message = ""
            if obj.status ~= nil then
              if obj.status.health ~= nil then
                hs.status = obj.status.health.status
                if obj.status.health.message ~= nil then
                  hs.message = obj.status.health.message
                end
              end
            end
            return hs
        networking.k8s.io/Ingress: # https://argo-cd.readthedocs.io/en/stable/faq/#why-is-my-application-stuck-in-progressing-state
          health.lua: |
            hs = {}
            hs.status = "Healthy"
            return hs
    secret:
      server.secretkey: $argo-cd-auth-tokens:server-secret-key
      accounts.terraform.tokens: $argo-cd-auth-tokens:terraform-tokens
  dex:
    enabled: false

# TODO Enable NetworkPolicies and add custom ones if necessary (such as by the Traefik reverse proxy)
